---
title: "5.5million"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
setwd('/Users/xunwang/Box Sync/Edward Bioinformatics course/bioinformatics/')
knn_ini <- read.delim(file="knn_.099mil.csv", sep=",")
```

------------ Knn -------------
```{r}
library('FNN')
library(igraph)
library(dplyr)
raw_links_1<-knn.dist(select(knn_ini, aromatic, gravy, insta, isoelectric, flexibility), k=1)
raw_links_2<-knn.index(select(knn_ini, aromatic, gravy, insta, isoelectric, flexibility), k=1)
links<- data.frame(start=1:nrow(knn_ini), finish = raw_links_2, weight = raw_links_1)
```

------------to draw the nearest neighbor graph-------------------
```{r}
nodes<- cbind(id = c(1:nrow(knn_ini)),knn_ini)
nn_net_.099mil <- graph.data.frame(d=links, vertices=nodes, directed=T) 
plot(nn_net_.099mil, edge.arrow.size=.4, vertex.size=4, vertex.label = NA, edge.color="grey",
vertex.color="orange", vertex.frame.color="white", layout=layout.fruchterman.reingold)
```

------ Here I tried to save the graph, but failed. This is probably because the graph was generated by igraph, not ggplot. 
The type of variable of the plot is NULL(empty). I tried to export this type of graph but failed...
```{r}
library('ggplot2')
lib_100000<- plot(nn_net_.099mil, edge.arrow.size=.4, vertex.size=4, vertex.label = NA, edge.color="grey",
vertex.color="orange", vertex.frame.color="white", layout=layout.fruchterman.reingold)
ggsave('lib_100000.png',lib_100000,dpi = 300)
#ggsave(filename, plot = last_plot(), device = NULL, path = NULL,
#scale = 1, width = NA, height = NA, units = c("in", "cm", "mm"),
#dpi = 300, limitsize = TRUE, ...)
```

------- Here is the density distribution of the "distances to the nearest neighbor"-------
```{r}
library(ggplot2)
library(cowplot)
weight_100000<-plot(density(knn_ini$weight))
save_plot(filename="weight_100000.png",weight_100000)
```

